// Catálogo de tecnologías del SDD Universal
// Generado desde catalogo_tecnologias_software.xlsx (hoja "Todo"). No editar a mano:
// regenerar desde la planilla y volver a exportar, o agregar filas nuevas en tecnologias.md.
// n=nombre · c=categoría · sc=subcategoría · t=tipo · e=ecosistema · f=familia (para filtrar) · u=uso · os=open source
const TECH = [
  {"n": "Assembly", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Assembly", "u": "Low-level", "os": true},
  {"n": "C", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "C / C++", "u": "Sistemas/embedded", "os": true},
  {"n": "C#", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "C# / .NET", "u": ".NET/gaming", "os": true},
  {"n": "C++", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "C / C++", "u": "Gaming/sistemas", "os": true},
  {"n": "Dart", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Dart", "u": "Mobile/Flutter", "os": true},
  {"n": "Fortran", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Fortran", "u": "Ciencia/ingeniería", "os": true},
  {"n": "Go", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Go", "u": "Backend/cloud", "os": true},
  {"n": "Haskell", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Haskell", "u": "Programación funcional", "os": true},
  {"n": "Java", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Java / JVM", "u": "Backend/enterprise", "os": true},
  {"n": "JavaScript", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "JavaScript / TypeScript", "u": "Frontend/backend", "os": true},
  {"n": "Kotlin", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Java / JVM", "u": "Android/backend", "os": true},
  {"n": "Lua", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Lua", "u": "Scripting/gaming", "os": true},
  {"n": "MATLAB", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "MATLAB", "u": "Ingeniería/cálculo", "os": false},
  {"n": "Objective-C", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Swift / Objective-C", "u": "Apple/legacy", "os": true},
  {"n": "Perl", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Perl", "u": "Automatización", "os": true},
  {"n": "PHP", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "PHP", "u": "Web", "os": true},
  {"n": "Python", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Python", "u": "IA/backend/data science", "os": true},
  {"n": "R", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "R", "u": "Data science/estadística", "os": true},
  {"n": "Ruby", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Ruby", "u": "Web", "os": true},
  {"n": "Rust", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Rust", "u": "Sistemas/backend", "os": true},
  {"n": "Scala", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Java / JVM", "u": "Backend/Big Data", "os": true},
  {"n": "SQL", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "SQL", "u": "Bases de datos", "os": true},
  {"n": "Swift", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Swift / Objective-C", "u": "Apple/mobile", "os": true},
  {"n": "TypeScript", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "JavaScript / TypeScript", "u": "Frontend/backend", "os": true},
  {"n": "Visual Basic", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Visual Basic", "u": "Windows/enterprise", "os": false},
  {"n": ".NET MAUI", "c": "Frameworks", "sc": "", "t": "Framework", "e": "C#", "f": "C# / .NET", "u": "Multiplatform", "os": true},
  {"n": "Actix Web", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Rust", "f": "Rust", "u": "Backend/API", "os": true},
  {"n": "AdonisJS", "c": "Frameworks", "sc": "", "t": "Framework", "e": "TypeScript", "f": "JavaScript / TypeScript", "u": "Backend", "os": true},
  {"n": "Angular", "c": "Frameworks", "sc": "", "t": "Framework", "e": "TypeScript", "f": "JavaScript / TypeScript", "u": "Frontend", "os": true},
  {"n": "ASP.NET Core", "c": "Frameworks", "sc": "", "t": "Framework", "e": "C#", "f": "C# / .NET", "u": "Backend/web", "os": true},
  {"n": "Axum", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Rust", "f": "Rust", "u": "Backend/API", "os": true},
  {"n": "Backbone.js", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript", "f": "JavaScript / TypeScript", "u": "Web", "os": true},
  {"n": "Beego", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Go", "f": "Go", "u": "Web/backend", "os": true},
  {"n": "CakePHP", "c": "Frameworks", "sc": "", "t": "Framework", "e": "PHP", "f": "PHP", "u": "Web", "os": true},
  {"n": "CodeIgniter", "c": "Frameworks", "sc": "", "t": "Framework", "e": "PHP", "f": "PHP", "u": "Web", "os": true},
  {"n": "Django", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Python", "f": "Python", "u": "Backend/web", "os": true},
  {"n": "Echo", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Go", "f": "Go", "u": "Backend/API", "os": true},
  {"n": "Ember.js", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript", "f": "JavaScript / TypeScript", "u": "Web", "os": true},
  {"n": "Express.js", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Backend/API", "os": true},
  {"n": "FastAPI", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Python", "f": "Python", "u": "API/backend", "os": true},
  {"n": "Fastify", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Backend/API", "os": true},
  {"n": "Fiber", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Go", "f": "Go", "u": "Backend/API", "os": true},
  {"n": "Flask", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Python", "f": "Python", "u": "Web/API", "os": true},
  {"n": "Flutter", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Dart", "f": "Dart", "u": "Mobile/multiplatform", "os": true},
  {"n": "Gatsby", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript/React", "f": "JavaScript / TypeScript", "u": "Static web", "os": true},
  {"n": "Gin", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Go", "f": "Go", "u": "Backend/API", "os": true},
  {"n": "Grails", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Groovy", "f": "Java / JVM", "u": "Web", "os": true},
  {"n": "Hapi.js", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript", "f": "JavaScript / TypeScript", "u": "Backend/API", "os": true},
  {"n": "Koa.js", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript", "f": "JavaScript / TypeScript", "u": "Backend/API", "os": true},
  {"n": "Laravel", "c": "Frameworks", "sc": "", "t": "Framework", "e": "PHP", "f": "PHP", "u": "Backend/web", "os": true},
  {"n": "Meteor", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript", "f": "JavaScript / TypeScript", "u": "Full-stack", "os": true},
  {"n": "Micronaut", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Java/Kotlin/Groovy", "f": "Java / JVM", "u": "Microservices", "os": true},
  {"n": "NestJS", "c": "Frameworks", "sc": "", "t": "Framework", "e": "TypeScript", "f": "JavaScript / TypeScript", "u": "Backend", "os": true},
  {"n": "Next.js", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Full-stack web", "os": true},
  {"n": "Nuxt", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Web", "os": true},
  {"n": "Phoenix", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Elixir", "f": "Elixir / Erlang", "u": "Web/backend", "os": true},
  {"n": "Play Framework", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Java/Scala", "f": "Java / JVM", "u": "Web/backend", "os": true},
  {"n": "Quarkus", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Java", "f": "Java / JVM", "u": "Cloud/microservices/backend", "os": true},
  {"n": "React Native", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Mobile", "os": true},
  {"n": "Remix", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Web", "os": true},
  {"n": "Rocket", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Rust", "f": "Rust", "u": "Web/backend", "os": true},
  {"n": "Ruby on Rails", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Ruby", "f": "Ruby", "u": "Web", "os": true},
  {"n": "Slim", "c": "Frameworks", "sc": "", "t": "Framework", "e": "PHP", "f": "PHP", "u": "API/web", "os": true},
  {"n": "Spring Boot", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Java", "f": "Java / JVM", "u": "Backend/enterprise", "os": true},
  {"n": "SvelteKit", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Web", "os": true},
  {"n": "Symfony", "c": "Frameworks", "sc": "", "t": "Framework", "e": "PHP", "f": "PHP", "u": "Web", "os": true},
  {"n": "Vapor", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Swift", "f": "Swift / Objective-C", "u": "Backend/API", "os": true},
  {"n": "Vert.x", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Java/JVM", "f": "Java / JVM", "u": "Reactive applications", "os": true},
  {"n": "Vue.js", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Frontend", "os": true},
  {"n": "Yii", "c": "Frameworks", "sc": "", "t": "Framework", "e": "PHP", "f": "PHP", "u": "Web", "os": true},
  {"n": "Axios", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "HTTP", "os": true},
  {"n": "Beautiful Soup", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "Python", "f": "Python", "u": "Web scraping", "os": true},
  {"n": "D3.js", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "JavaScript", "f": "JavaScript / TypeScript", "u": "Visualización", "os": true},
  {"n": "jQuery", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "JavaScript", "f": "JavaScript / TypeScript", "u": "DOM", "os": true},
  {"n": "Lodash", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "JavaScript", "f": "JavaScript / TypeScript", "u": "Utilidades", "os": true},
  {"n": "Matplotlib", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "Python", "f": "Python", "u": "Visualización", "os": true},
  {"n": "NumPy", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "Python", "f": "Python", "u": "Cálculo numérico", "os": true},
  {"n": "Pandas", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "Python", "f": "Python", "u": "Datos", "os": true},
  {"n": "Pydantic", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "Python", "f": "Python", "u": "Validación de datos", "os": true},
  {"n": "PyTorch", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "Python / C++", "f": "Python", "u": "IA y Machine Learning", "os": true},
  {"n": "React", "c": "Bibliotecas", "sc": "", "t": "Library", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Frontend", "os": true},
  {"n": "Redux", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Estado", "os": true},
  {"n": "Requests", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "Python", "f": "Python", "u": "HTTP", "os": true},
  {"n": "Scikit-learn", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "Python", "f": "Python", "u": "Machine Learning", "os": true},
  {"n": "Socket.IO", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "JavaScript", "f": "JavaScript / TypeScript", "u": "Tiempo real", "os": true},
  {"n": "SQLAlchemy", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "Python", "f": "Python", "u": "ORM/database", "os": true},
  {"n": "TensorFlow", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "Python / C++", "f": "Python", "u": "IA y Machine Learning", "os": true},
  {"n": "Three.js", "c": "Bibliotecas", "sc": "", "t": "Biblioteca", "e": "JavaScript", "f": "JavaScript / TypeScript", "u": "3D/WebGL", "os": true},
  {"n": "Node.js", "c": "Backend", "sc": "Runtime", "t": "Runtime", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Backend", "os": true},
  {"n": "PostgreSQL", "c": "Bases de datos", "sc": "", "t": "Base de datos", "e": "SQL", "f": "SQL", "u": "Relacional", "os": true},
  {"n": "Vercel", "c": "Deployment/PaaS", "sc": "", "t": "PaaS", "e": "JS/TS", "f": "JavaScript / TypeScript", "u": "Frontend/Full-stack", "os": false},
  {"n": "AWS", "c": "Cloud", "sc": "", "t": "Cloud", "e": "Multilenguaje", "f": "Multilenguaje", "u": "Infraestructura", "os": false},
  {"n": "Kubernetes", "c": "DevOps", "sc": "", "t": "Tool", "e": "", "f": "", "u": "Orquestación", "os": true},
  {"n": "Jest", "c": "Testing", "sc": "", "t": "Tool", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Testing", "os": true},
  {"n": "Playwright", "c": "Testing", "sc": "", "t": "Tool", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Testing web", "os": true},
  {"n": "OWASP ZAP", "c": "Seguridad", "sc": "", "t": "Tool", "e": "", "f": "", "u": "Seguridad web", "os": true},
  {"n": "GPT", "c": "IA - Modelos", "sc": "", "t": "Modelo IA", "e": "", "f": "", "u": "LLM", "os": false},
  {"n": "Godot", "c": "Videojuegos", "sc": "Game Engine", "t": "Game Engine", "e": "GDScript/C++", "f": "Godot (GDScript)", "u": "Videojuegos", "os": true},
  {"n": "Unity", "c": "Videojuegos", "sc": "Game Engine", "t": "Game Engine", "e": "C#", "f": "C# / .NET", "u": "Videojuegos", "os": false},
  {"n": "Unreal Engine", "c": "Videojuegos", "sc": "Game Engine", "t": "Game Engine", "e": "C++", "f": "C / C++", "u": "Videojuegos", "os": false},
  {"n": "Puppeteer", "c": "Developer Tools", "sc": "", "t": "Tool", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Automatización web", "os": true},
  {"n": "Elixir", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Elixir", "u": "Backend concurrente", "os": true},
  {"n": "Zig", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Zig", "u": "Sistemas", "os": true},
  {"n": "Julia", "c": "Lenguajes", "sc": "", "t": "Lenguaje", "e": "", "f": "Julia", "u": "Ciencia/cálculo", "os": true},
  {"n": "Svelte", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Frontend", "os": true},
  {"n": "Astro", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Sitios de contenido", "os": true},
  {"n": "Electron", "c": "Frameworks", "sc": "", "t": "Framework", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Apps de escritorio", "os": true},
  {"n": "Tauri", "c": "Frameworks", "sc": "", "t": "Framework", "e": "Rust + JS", "f": "Rust", "u": "Apps de escritorio livianas", "os": true},
  {"n": "Bun", "c": "Backend", "sc": "Runtime", "t": "Runtime", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Backend/tooling rápido", "os": true},
  {"n": "Deno", "c": "Backend", "sc": "Runtime", "t": "Runtime", "e": "JavaScript/TypeScript", "f": "JavaScript / TypeScript", "u": "Backend seguro por default", "os": true},
  {"n": "SQLite", "c": "Bases de datos", "sc": "", "t": "Base de datos", "e": "SQL", "f": "SQL", "u": "Embebida/local", "os": true},
  {"n": "MongoDB", "c": "Bases de datos", "sc": "", "t": "Base de datos", "e": "", "f": "", "u": "Documentos/NoSQL", "os": true},
  {"n": "Redis", "c": "Bases de datos", "sc": "", "t": "Base de datos", "e": "", "f": "", "u": "Cache/tiempo real", "os": true},
  {"n": "DuckDB", "c": "Bases de datos", "sc": "", "t": "Base de datos", "e": "SQL", "f": "SQL", "u": "Análisis local", "os": true},
  {"n": "Supabase", "c": "Bases de datos", "sc": "BaaS", "t": "BaaS", "e": "SQL", "f": "SQL", "u": "Postgres + auth + API", "os": true},
  {"n": "Azure", "c": "Cloud", "sc": "", "t": "Cloud", "e": "Multilenguaje", "f": "Multilenguaje", "u": "Infraestructura", "os": false},
  {"n": "Docker", "c": "DevOps", "sc": "", "t": "Tool", "e": "", "f": "", "u": "Contenedores", "os": true},
  {"n": "GitHub Actions", "c": "DevOps", "sc": "", "t": "Tool", "e": "", "f": "", "u": "CI/CD", "os": false},
  {"n": "Claude", "c": "IA - Modelos", "sc": "", "t": "Modelo IA", "e": "", "f": "", "u": "LLM/agentes", "os": false},
  {"n": "Ollama", "c": "IA - Modelos", "sc": "", "t": "Tool", "e": "", "f": "", "u": "LLMs locales", "os": true},
];
